// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome')
const assert = require('assert')

describe('Login - Successful', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome')
      // .setChromeOptions(new chrome.Options().headless())
      .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login - Invalid Password', async function() {
    await driver.get("https://ipayment.phgo.xyz/")
    // await driver.manage().window().setRect({ width: 1680, height: 1025 })
    await driver.findElement(By.linkText("Log Masuk")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("cliffordlouhart@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Abcd1234!")
    await driver.findElement(By.css(".checkbox > label")).click()
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.css(".invalid-feedback")).getText())
  });

  it('Login - Successful', async function() {
    await driver.get("https://ipayment.phgo.xyz")
    // await driver.manage().window().setRect({ width: 1680, height: 1025 })
    if(! await driver.findElement(By.linkText("Log Masuk"))) {
      await driver.findElement(By.linkText("Clifford Louhart")).click()
      await driver.findElement(By.linkText("Log Keluar")).click()
     }
    // await driver.findElement(By.linkText("Log Masuk")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("cliffordlouhart@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Abcd1234!@")
    await driver.findElement(By.css(".checkbox > label")).click()
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.linkText("Clifford Louhart")).getText())
    await driver.findElement(By.linkText("Clifford Louhart")).click()
    await driver.findElement(By.linkText("Log Keluar")).click()
  });
})
